const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const ADD_QUANTITY = "ADD_QUANTITY";
const SUB_QUANITY = "SUB_QUANITY";


export{ADD_QUANTITY, ADD_TO_CART, REMOVE_FROM_CART, CLEAR_CART, SUB_QUANITY}